### ISSUE TITLE
Zenodo link not working

### ISSUE THREAD

**Issue by SANCHES-Pedro** [biocompibens/phenexplain#1]
Thanks for the amazing work! The Zenodo link for the datasets is not working.

https://zenodo.org/record/8287453

Are all the datasets available?

**Comment by agenoves** [comment]
Not sure what you mean as It seems to work from what I can see right now. On 11 Apr 2024, at 17:20, Pedro P. Sanchez ***@***.***> wrote:﻿
Thanks for the amazing work! The Zenodo link for the datasets is not working.
https://zenodo.org/record/8287453
Are all the datasets available?

**Comment by SANCHES-Pedro** [comment]
Sorry, weirdly, it's working now.

Thanks for the prompt response, regardless. Great work again.
